// Date: 11.8.2013 0:50:28
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modelapiary extends ModelBase
{
  //fields
    ModelRenderer leg;
    ModelRenderer leg;
    ModelRenderer leg;
    ModelRenderer leg;
    ModelRenderer board;
    ModelRenderer apiary1;
    ModelRenderer apiary2;
    ModelRenderer thingy;
  
  public Modelapiary()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      leg = new ModelRenderer(this, 0, 0);
      leg.addBox(0F, 0F, 0F, 1, 1, 1);
      leg.setRotationPoint(-7F, 23F, 4F);
      leg.setTextureSize(64, 32);
      leg.mirror = true;
      setRotation(leg, 0F, 0F, 0F);
      leg = new ModelRenderer(this, 0, 0);
      leg.addBox(0F, 0F, 0F, 1, 1, 1);
      leg.setRotationPoint(-7F, 23F, -4F);
      leg.setTextureSize(64, 32);
      leg.mirror = true;
      setRotation(leg, 0F, 0F, 0F);
      leg = new ModelRenderer(this, 0, 0);
      leg.addBox(0F, 0F, 0F, 1, 1, 1);
      leg.setRotationPoint(6F, 23F, 4F);
      leg.setTextureSize(64, 32);
      leg.mirror = true;
      setRotation(leg, 0F, 0F, 0F);
      leg = new ModelRenderer(this, 0, 0);
      leg.addBox(0F, 0F, 0F, 1, 1, 1);
      leg.setRotationPoint(6F, 23F, -4F);
      leg.setTextureSize(64, 32);
      leg.mirror = true;
      setRotation(leg, 0F, 0F, 0F);
      board = new ModelRenderer(this, 0, 2);
      board.addBox(0F, 0F, 0F, 16, 1, 9);
      board.setRotationPoint(-8F, 22F, -4F);
      board.setTextureSize(64, 32);
      board.mirror = true;
      setRotation(board, 0F, 0F, 0F);
      apiary1 = new ModelRenderer(this, 0, 12);
      apiary1.addBox(1F, 0F, 0F, 15, 5, 6);
      apiary1.setRotationPoint(-8.666667F, 17F, -2F);
      apiary1.setTextureSize(64, 32);
      apiary1.mirror = true;
      setRotation(apiary1, 0F, 0.0371786F, 0F);
      apiary2 = new ModelRenderer(this, 0, 12);
      apiary2.addBox(0F, 0F, 0F, 15, 5, 6);
      apiary2.setRotationPoint(-7.7F, 12F, -3F);
      apiary2.setTextureSize(64, 32);
      apiary2.mirror = true;
      setRotation(apiary2, 0F, -0.1115358F, 0F);
      thingy = new ModelRenderer(this, 5, 0);
      thingy.addBox(0F, 0F, 0F, 2, 1, 1);
      thingy.setRotationPoint(5F, 21F, 4F);
      thingy.setTextureSize(64, 32);
      thingy.mirror = true;
      setRotation(thingy, 0F, -0.0743572F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    leg.render(f5);
    leg.render(f5);
    leg.render(f5);
    leg.render(f5);
    board.render(f5);
    apiary1.render(f5);
    apiary2.render(f5);
    thingy.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
